[2023-05-23 10:52:47 -0500] [22600] [INFO] Starting gunicorn 20.1.0
[2023-05-23 10:52:47 -0500] [22600] [INFO] Listening at: http://127.0.0.1:5000 (22600)
[2023-05-23 10:52:47 -0500] [22600] [INFO] Using worker: sync
[2023-05-23 10:52:47 -0500] [22603] [INFO] Booting worker with pid: 22603
[2023-05-23 10:52:47 -0500] [22604] [INFO] Booting worker with pid: 22604
[2023-05-23 10:52:47 -0500] [22605] [INFO] Booting worker with pid: 22605
[2023-05-23 10:54:12 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:22605)
[2023-05-23 10:54:12 -0500] [22605] [INFO] Worker exiting (pid: 22605)
[2023-05-23 10:54:12 -0500] [22851] [INFO] Booting worker with pid: 22851
[2023-05-23 10:56:00 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:22851)
[2023-05-23 10:56:00 -0500] [22851] [INFO] Worker exiting (pid: 22851)
[2023-05-23 10:56:00 -0500] [23158] [INFO] Booting worker with pid: 23158
[2023-05-23 11:02:25 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:22604)
[2023-05-23 11:02:25 -0500] [22604] [INFO] Worker exiting (pid: 22604)
[2023-05-23 11:02:25 -0500] [23768] [INFO] Booting worker with pid: 23768
[2023-05-23 11:06:25 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:23158)
[2023-05-23 11:06:25 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:23768)
[2023-05-23 11:06:25 -0500] [23158] [INFO] Worker exiting (pid: 23158)
[2023-05-23 11:06:25 -0500] [23768] [INFO] Worker exiting (pid: 23768)
[2023-05-23 11:06:25 -0500] [24023] [INFO] Booting worker with pid: 24023
[2023-05-23 11:06:25 -0500] [24024] [INFO] Booting worker with pid: 24024
[2023-05-23 11:07:53 -0500] [22600] [CRITICAL] WORKER TIMEOUT (pid:22603)
[2023-05-23 11:07:53 -0500] [22603] [INFO] Worker exiting (pid: 22603)
[2023-05-23 11:07:53 -0500] [24174] [INFO] Booting worker with pid: 24174
[2023-05-23 11:09:46 -0500] [24174] [INFO] Worker exiting (pid: 24174)
[2023-05-23 11:09:46 -0500] [24023] [INFO] Worker exiting (pid: 24023)
[2023-05-23 11:09:46 -0500] [24024] [INFO] Worker exiting (pid: 24024)
[2023-05-23 11:09:46 -0500] [22600] [INFO] Handling signal: term
[2023-05-23 11:09:46 -0500] [22600] [WARNING] Worker with pid 24024 was terminated due to signal 15
[2023-05-23 11:09:46 -0500] [22600] [WARNING] Worker with pid 24174 was terminated due to signal 15
[2023-05-23 11:09:46 -0500] [22600] [WARNING] Worker with pid 24023 was terminated due to signal 15
[2023-05-23 11:09:46 -0500] [22600] [INFO] Shutting down: Master
[2023-05-23 11:09:47 -0500] [24528] [INFO] Starting gunicorn 20.1.0
[2023-05-23 11:09:47 -0500] [24528] [INFO] Listening at: http://127.0.0.1:5000 (24528)
[2023-05-23 11:09:47 -0500] [24528] [INFO] Using worker: sync
[2023-05-23 11:09:47 -0500] [24531] [INFO] Booting worker with pid: 24531
[2023-05-23 11:09:47 -0500] [24532] [INFO] Booting worker with pid: 24532
[2023-05-23 11:09:47 -0500] [24533] [INFO] Booting worker with pid: 24533
[2023-05-23 11:10:37 -0500] [24528] [CRITICAL] WORKER TIMEOUT (pid:24531)
[2023-05-23 11:10:37 -0500] [24531] [INFO] Worker exiting (pid: 24531)
[2023-05-23 11:10:37 -0500] [24626] [INFO] Booting worker with pid: 24626
[2023-05-23 11:18:14 -0500] [24533] [INFO] Worker exiting (pid: 24533)
[2023-05-23 11:18:14 -0500] [24626] [INFO] Worker exiting (pid: 24626)
[2023-05-23 11:18:14 -0500] [24532] [INFO] Worker exiting (pid: 24532)
[2023-05-23 11:18:14 -0500] [24528] [INFO] Handling signal: term
[2023-05-23 11:18:14 -0500] [24528] [WARNING] Worker with pid 24626 was terminated due to signal 15
[2023-05-23 11:18:14 -0500] [24528] [WARNING] Worker with pid 24533 was terminated due to signal 15
[2023-05-23 11:18:14 -0500] [24528] [WARNING] Worker with pid 24532 was terminated due to signal 15
[2023-05-23 11:18:15 -0500] [24528] [INFO] Shutting down: Master
[2023-05-23 11:46:11 -0500] [28156] [INFO] Starting gunicorn 20.1.0
[2023-05-23 11:46:11 -0500] [28156] [INFO] Listening at: http://127.0.0.1:5000 (28156)
[2023-05-23 11:46:11 -0500] [28156] [INFO] Using worker: sync
[2023-05-23 11:46:11 -0500] [28158] [INFO] Booting worker with pid: 28158
[2023-05-23 11:46:11 -0500] [28159] [INFO] Booting worker with pid: 28159
[2023-05-23 11:46:11 -0500] [28160] [INFO] Booting worker with pid: 28160
[2023-05-23 11:46:11 -0500] [28161] [INFO] Booting worker with pid: 28161
[2023-05-23 11:46:11 -0500] [28162] [INFO] Booting worker with pid: 28162
[2023-05-23 11:46:12 -0500] [28163] [INFO] Booting worker with pid: 28163
[2023-05-23 11:46:12 -0500] [28164] [INFO] Booting worker with pid: 28164
[2023-05-23 11:46:12 -0500] [28165] [INFO] Booting worker with pid: 28165
[2023-05-23 11:46:12 -0500] [28166] [INFO] Booting worker with pid: 28166
[2023-05-23 11:55:15 -0500] [28159] [INFO] Worker exiting (pid: 28159)
[2023-05-23 11:55:15 -0500] [28162] [INFO] Worker exiting (pid: 28162)
[2023-05-23 11:55:15 -0500] [28160] [INFO] Worker exiting (pid: 28160)
[2023-05-23 11:55:15 -0500] [28156] [INFO] Handling signal: term
[2023-05-23 11:55:15 -0500] [28163] [INFO] Worker exiting (pid: 28163)
[2023-05-23 11:55:15 -0500] [28158] [INFO] Worker exiting (pid: 28158)
[2023-05-23 11:55:15 -0500] [28165] [INFO] Worker exiting (pid: 28165)
[2023-05-23 11:55:15 -0500] [28166] [INFO] Worker exiting (pid: 28166)
[2023-05-23 11:55:15 -0500] [28164] [INFO] Worker exiting (pid: 28164)
[2023-05-23 11:55:15 -0500] [28156] [WARNING] Worker with pid 28159 was terminated due to signal 15
[2023-05-23 11:55:15 -0500] [28156] [WARNING] Worker with pid 28166 was terminated due to signal 15
[2023-05-23 11:55:15 -0500] [28161] [INFO] Worker exiting (pid: 28161)
[2023-05-23 11:55:15 -0500] [28156] [WARNING] Worker with pid 28162 was terminated due to signal 15
[2023-05-23 11:55:15 -0500] [28156] [WARNING] Worker with pid 28165 was terminated due to signal 15
[2023-05-23 11:55:15 -0500] [28156] [WARNING] Worker with pid 28160 was terminated due to signal 15
[2023-05-23 11:55:16 -0500] [28156] [INFO] Shutting down: Master
[2023-05-23 12:03:05 -0500] [29352] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:03:05 -0500] [29352] [INFO] Listening at: http://127.0.0.1:5000 (29352)
[2023-05-23 12:03:05 -0500] [29352] [INFO] Using worker: sync
[2023-05-23 12:03:05 -0500] [29357] [INFO] Booting worker with pid: 29357
[2023-05-23 12:03:05 -0500] [29358] [INFO] Booting worker with pid: 29358
[2023-05-23 12:03:05 -0500] [29359] [INFO] Booting worker with pid: 29359
[2023-05-23 12:03:05 -0500] [29360] [INFO] Booting worker with pid: 29360
[2023-05-23 12:03:05 -0500] [29361] [INFO] Booting worker with pid: 29361
[2023-05-23 12:03:05 -0500] [29362] [INFO] Booting worker with pid: 29362
[2023-05-23 12:03:06 -0500] [29363] [INFO] Booting worker with pid: 29363
[2023-05-23 12:03:06 -0500] [29364] [INFO] Booting worker with pid: 29364
[2023-05-23 12:03:06 -0500] [29369] [INFO] Booting worker with pid: 29369
[2023-05-23 12:12:13 -0500] [29369] [INFO] Worker exiting (pid: 29369)
[2023-05-23 12:12:13 -0500] [29352] [INFO] Handling signal: term
[2023-05-23 12:12:13 -0500] [29360] [INFO] Worker exiting (pid: 29360)
[2023-05-23 12:12:13 -0500] [29357] [INFO] Worker exiting (pid: 29357)
[2023-05-23 12:12:13 -0500] [29359] [INFO] Worker exiting (pid: 29359)
[2023-05-23 12:12:13 -0500] [29363] [INFO] Worker exiting (pid: 29363)
[2023-05-23 12:12:13 -0500] [29364] [INFO] Worker exiting (pid: 29364)
[2023-05-23 12:12:13 -0500] [29358] [INFO] Worker exiting (pid: 29358)
[2023-05-23 12:12:13 -0500] [29352] [WARNING] Worker with pid 29369 was terminated due to signal 15
[2023-05-23 12:12:13 -0500] [29361] [INFO] Worker exiting (pid: 29361)
[2023-05-23 12:12:13 -0500] [29362] [INFO] Worker exiting (pid: 29362)
[2023-05-23 12:12:14 -0500] [29352] [INFO] Shutting down: Master
[2023-05-23 12:12:14 -0500] [30686] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:12:14 -0500] [30686] [INFO] Listening at: http://127.0.0.1:5000 (30686)
[2023-05-23 12:12:14 -0500] [30686] [INFO] Using worker: sync
[2023-05-23 12:12:14 -0500] [30701] [INFO] Booting worker with pid: 30701
[2023-05-23 12:12:14 -0500] [30702] [INFO] Booting worker with pid: 30702
[2023-05-23 12:12:14 -0500] [30703] [INFO] Booting worker with pid: 30703
[2023-05-23 12:12:14 -0500] [30704] [INFO] Booting worker with pid: 30704
[2023-05-23 12:12:15 -0500] [30705] [INFO] Booting worker with pid: 30705
[2023-05-23 12:12:15 -0500] [30706] [INFO] Booting worker with pid: 30706
[2023-05-23 12:12:15 -0500] [30707] [INFO] Booting worker with pid: 30707
[2023-05-23 12:12:15 -0500] [30708] [INFO] Booting worker with pid: 30708
[2023-05-23 12:12:15 -0500] [30709] [INFO] Booting worker with pid: 30709
[2023-05-23 12:13:14 -0500] [30708] [INFO] Worker exiting (pid: 30708)
[2023-05-23 12:13:14 -0500] [30701] [INFO] Worker exiting (pid: 30701)
[2023-05-23 12:13:14 -0500] [30702] [INFO] Worker exiting (pid: 30702)
[2023-05-23 12:13:14 -0500] [30703] [INFO] Worker exiting (pid: 30703)
[2023-05-23 12:13:14 -0500] [30707] [INFO] Worker exiting (pid: 30707)
[2023-05-23 12:13:14 -0500] [30704] [INFO] Worker exiting (pid: 30704)
[2023-05-23 12:13:14 -0500] [30706] [INFO] Worker exiting (pid: 30706)
[2023-05-23 12:13:14 -0500] [30686] [INFO] Handling signal: term
[2023-05-23 12:13:14 -0500] [30705] [INFO] Worker exiting (pid: 30705)
[2023-05-23 12:13:14 -0500] [30709] [INFO] Worker exiting (pid: 30709)
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30701 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30705 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30708 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30706 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30703 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30704 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30702 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [WARNING] Worker with pid 30707 was terminated due to signal 15
[2023-05-23 12:13:14 -0500] [30686] [INFO] Shutting down: Master
[2023-05-23 12:13:15 -0500] [30847] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:13:15 -0500] [30847] [INFO] Listening at: http://127.0.0.1:5000 (30847)
[2023-05-23 12:13:15 -0500] [30847] [INFO] Using worker: sync
[2023-05-23 12:13:15 -0500] [30849] [INFO] Booting worker with pid: 30849
[2023-05-23 12:13:15 -0500] [30850] [INFO] Booting worker with pid: 30850
[2023-05-23 12:13:15 -0500] [30851] [INFO] Booting worker with pid: 30851
[2023-05-23 12:13:15 -0500] [30852] [INFO] Booting worker with pid: 30852
[2023-05-23 12:13:15 -0500] [30853] [INFO] Booting worker with pid: 30853
[2023-05-23 12:13:15 -0500] [30854] [INFO] Booting worker with pid: 30854
[2023-05-23 12:13:15 -0500] [30855] [INFO] Booting worker with pid: 30855
[2023-05-23 12:13:15 -0500] [30865] [INFO] Booting worker with pid: 30865
[2023-05-23 12:13:15 -0500] [30866] [INFO] Booting worker with pid: 30866
[2023-05-23 12:16:38 -0500] [30852] [INFO] Worker exiting (pid: 30852)
[2023-05-23 12:16:38 -0500] [30849] [INFO] Worker exiting (pid: 30849)
[2023-05-23 12:16:38 -0500] [30847] [INFO] Handling signal: term
[2023-05-23 12:16:38 -0500] [30850] [INFO] Worker exiting (pid: 30850)
[2023-05-23 12:16:38 -0500] [30851] [INFO] Worker exiting (pid: 30851)
[2023-05-23 12:16:38 -0500] [30853] [INFO] Worker exiting (pid: 30853)
[2023-05-23 12:16:38 -0500] [30865] [INFO] Worker exiting (pid: 30865)
[2023-05-23 12:16:38 -0500] [30866] [INFO] Worker exiting (pid: 30866)
[2023-05-23 12:16:38 -0500] [30855] [INFO] Worker exiting (pid: 30855)
[2023-05-23 12:16:38 -0500] [30847] [WARNING] Worker with pid 30852 was terminated due to signal 15
[2023-05-23 12:16:38 -0500] [30847] [WARNING] Worker with pid 30849 was terminated due to signal 15
[2023-05-23 12:16:38 -0500] [30854] [INFO] Worker exiting (pid: 30854)
[2023-05-23 12:16:41 -0500] [30847] [INFO] Shutting down: Master
[2023-05-23 12:16:41 -0500] [31606] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:16:41 -0500] [31606] [INFO] Listening at: http://127.0.0.1:5000 (31606)
[2023-05-23 12:16:41 -0500] [31606] [INFO] Using worker: sync
[2023-05-23 12:16:41 -0500] [31610] [INFO] Booting worker with pid: 31610
[2023-05-23 12:16:41 -0500] [31611] [INFO] Booting worker with pid: 31611
[2023-05-23 12:16:41 -0500] [31612] [INFO] Booting worker with pid: 31612
[2023-05-23 12:16:41 -0500] [31613] [INFO] Booting worker with pid: 31613
[2023-05-23 12:16:41 -0500] [31614] [INFO] Booting worker with pid: 31614
[2023-05-23 12:16:41 -0500] [31615] [INFO] Booting worker with pid: 31615
[2023-05-23 12:16:41 -0500] [31616] [INFO] Booting worker with pid: 31616
[2023-05-23 12:16:41 -0500] [31617] [INFO] Booting worker with pid: 31617
[2023-05-23 12:16:42 -0500] [31618] [INFO] Booting worker with pid: 31618
[2023-05-23 12:19:47 -0500] [31611] [INFO] Worker exiting (pid: 31611)
[2023-05-23 12:19:47 -0500] [31610] [INFO] Worker exiting (pid: 31610)
[2023-05-23 12:19:47 -0500] [31606] [INFO] Handling signal: term
[2023-05-23 12:19:47 -0500] [31613] [INFO] Worker exiting (pid: 31613)
[2023-05-23 12:19:47 -0500] [31612] [INFO] Worker exiting (pid: 31612)
[2023-05-23 12:19:47 -0500] [31614] [INFO] Worker exiting (pid: 31614)
[2023-05-23 12:19:47 -0500] [31616] [INFO] Worker exiting (pid: 31616)
[2023-05-23 12:19:47 -0500] [31615] [INFO] Worker exiting (pid: 31615)
[2023-05-23 12:19:47 -0500] [31617] [INFO] Worker exiting (pid: 31617)
[2023-05-23 12:19:47 -0500] [31618] [INFO] Worker exiting (pid: 31618)
[2023-05-23 12:19:49 -0500] [31606] [INFO] Shutting down: Master
[2023-05-23 12:19:49 -0500] [31742] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:19:49 -0500] [31742] [INFO] Listening at: http://127.0.0.1:5000 (31742)
[2023-05-23 12:19:49 -0500] [31742] [INFO] Using worker: sync
[2023-05-23 12:19:49 -0500] [31744] [INFO] Booting worker with pid: 31744
[2023-05-23 12:19:49 -0500] [31745] [INFO] Booting worker with pid: 31745
[2023-05-23 12:19:49 -0500] [31746] [INFO] Booting worker with pid: 31746
[2023-05-23 12:19:49 -0500] [31747] [INFO] Booting worker with pid: 31747
[2023-05-23 12:19:49 -0500] [31748] [INFO] Booting worker with pid: 31748
[2023-05-23 12:19:49 -0500] [31749] [INFO] Booting worker with pid: 31749
[2023-05-23 12:19:49 -0500] [31750] [INFO] Booting worker with pid: 31750
[2023-05-23 12:19:49 -0500] [31758] [INFO] Booting worker with pid: 31758
[2023-05-23 12:19:49 -0500] [31759] [INFO] Booting worker with pid: 31759
[2023-05-23 12:19:53 -0500] [31746] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31746] [INFO] Worker exiting (pid: 31746)
[2023-05-23 12:19:53 -0500] [31744] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31744] [INFO] Worker exiting (pid: 31744)
[2023-05-23 12:19:53 -0500] [31745] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31745] [INFO] Worker exiting (pid: 31745)
[2023-05-23 12:19:53 -0500] [31759] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31759] [INFO] Worker exiting (pid: 31759)
[2023-05-23 12:19:53 -0500] [31747] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31747] [INFO] Worker exiting (pid: 31747)
[2023-05-23 12:19:53 -0500] [31748] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31748] [INFO] Worker exiting (pid: 31748)
[2023-05-23 12:19:53 -0500] [31750] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:53 -0500] [31750] [INFO] Worker exiting (pid: 31750)
[2023-05-23 12:19:54 -0500] [31749] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:54 -0500] [31749] [INFO] Worker exiting (pid: 31749)
[2023-05-23 12:19:54 -0500] [31758] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 875, in import_string
    return getattr(module, obj_name)
AttributeError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
ImportError: module 'config' has no attribute 'py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/var/www/website-stuff/backend/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/website-stuff/backend/app/__init__.py", line 13, in <module>
    app.config.from_object('config.py')
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/config.py", line 161, in from_object
    obj = import_string(obj)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 881, in import_string
    raise ImportStringError(import_name, e).with_traceback(sys.exc_info()[2])
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/werkzeug/utils.py", line 877, in import_string
    raise ImportError(e)
werkzeug.utils.ImportStringError: import_string() failed for 'config.py'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' found in '/var/www/website-stuff/backend/config.py'.
- 'config.py' not found.

Original exception:

ImportError: module 'config' has no attribute 'py'
[2023-05-23 12:19:54 -0500] [31758] [INFO] Worker exiting (pid: 31758)
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31746 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31759 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31750 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31747 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31749 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31758 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31748 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [WARNING] Worker with pid 31745 was terminated due to signal 15
[2023-05-23 12:19:54 -0500] [31742] [INFO] Shutting down: Master
[2023-05-23 12:19:54 -0500] [31742] [INFO] Reason: Worker failed to boot.
[2023-05-23 12:20:56 -0500] [31904] [INFO] Starting gunicorn 20.1.0
[2023-05-23 12:20:56 -0500] [31904] [INFO] Listening at: http://127.0.0.1:5000 (31904)
[2023-05-23 12:20:56 -0500] [31904] [INFO] Using worker: sync
[2023-05-23 12:20:56 -0500] [31906] [INFO] Booting worker with pid: 31906
[2023-05-23 12:20:56 -0500] [31907] [INFO] Booting worker with pid: 31907
[2023-05-23 12:20:56 -0500] [31908] [INFO] Booting worker with pid: 31908
[2023-05-23 12:20:56 -0500] [31909] [INFO] Booting worker with pid: 31909
[2023-05-23 12:20:56 -0500] [31910] [INFO] Booting worker with pid: 31910
[2023-05-23 12:20:56 -0500] [31911] [INFO] Booting worker with pid: 31911
[2023-05-23 12:20:56 -0500] [31912] [INFO] Booting worker with pid: 31912
[2023-05-23 12:20:56 -0500] [31913] [INFO] Booting worker with pid: 31913
[2023-05-23 12:20:56 -0500] [31914] [INFO] Booting worker with pid: 31914
[2023-05-23 12:24:54 -0500] [31908] [INFO] Worker exiting (pid: 31908)
[2023-05-23 12:24:54 -0500] [31907] [INFO] Worker exiting (pid: 31907)
[2023-05-23 12:24:54 -0500] [31906] [INFO] Worker exiting (pid: 31906)
[2023-05-23 12:24:54 -0500] [31904] [INFO] Handling signal: term
[2023-05-23 12:24:54 -0500] [31909] [INFO] Worker exiting (pid: 31909)
[2023-05-23 12:24:54 -0500] [31910] [INFO] Worker exiting (pid: 31910)
[2023-05-23 12:24:54 -0500] [31912] [INFO] Worker exiting (pid: 31912)
[2023-05-23 12:24:54 -0500] [31911] [INFO] Worker exiting (pid: 31911)
[2023-05-23 12:24:54 -0500] [31913] [INFO] Worker exiting (pid: 31913)
[2023-05-23 12:24:54 -0500] [31914] [INFO] Worker exiting (pid: 31914)
[2023-05-23 12:24:54 -0500] [31904] [WARNING] Worker with pid 31911 was terminated due to signal 15
[2023-05-23 12:24:54 -0500] [31904] [WARNING] Worker with pid 31912 was terminated due to signal 15
[2023-05-23 12:24:54 -0500] [31904] [WARNING] Worker with pid 31914 was terminated due to signal 15
[2023-05-23 12:24:54 -0500] [31904] [WARNING] Worker with pid 31913 was terminated due to signal 15
[2023-05-23 12:24:54 -0500] [31904] [WARNING] Worker with pid 31909 was terminated due to signal 15
[2023-05-23 12:24:54 -0500] [31904] [INFO] Shutting down: Master
[2023-05-24 13:30:00 -0500] [1046] [INFO] Starting gunicorn 20.1.0
[2023-05-24 13:30:00 -0500] [1046] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:30:00 -0500] [1046] [ERROR] Retrying in 1 second.
[2023-05-24 13:30:01 -0500] [1046] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:30:01 -0500] [1046] [ERROR] Retrying in 1 second.
[2023-05-24 13:30:02 -0500] [1046] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:30:02 -0500] [1046] [ERROR] Retrying in 1 second.
[2023-05-24 13:30:03 -0500] [1046] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:30:03 -0500] [1046] [ERROR] Retrying in 1 second.
[2023-05-24 13:30:04 -0500] [1046] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:30:04 -0500] [1046] [ERROR] Retrying in 1 second.
[2023-05-24 13:30:05 -0500] [1046] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2023-05-24 13:34:43 -0500] [6007] [INFO] Starting gunicorn 20.1.0
[2023-05-24 13:34:43 -0500] [6007] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:34:43 -0500] [6007] [ERROR] Retrying in 1 second.
[2023-05-24 13:34:44 -0500] [6007] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:34:44 -0500] [6007] [ERROR] Retrying in 1 second.
[2023-05-24 13:34:45 -0500] [6007] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:34:45 -0500] [6007] [ERROR] Retrying in 1 second.
[2023-05-24 13:34:46 -0500] [6007] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:34:46 -0500] [6007] [ERROR] Retrying in 1 second.
[2023-05-24 13:34:47 -0500] [6007] [ERROR] Connection in use: ('127.0.0.1', 5000)
[2023-05-24 13:34:47 -0500] [6007] [ERROR] Retrying in 1 second.
[2023-05-24 13:34:48 -0500] [6007] [ERROR] Can't connect to ('127.0.0.1', 5000)
[2023-05-24 14:03:59 -0500] [15716] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:03:59 -0500] [15716] [INFO] Listening at: http://127.0.0.1:5000 (15716)
[2023-05-24 14:03:59 -0500] [15716] [INFO] Using worker: sync
[2023-05-24 14:03:59 -0500] [15736] [INFO] Booting worker with pid: 15736
[2023-05-24 14:03:59 -0500] [15740] [INFO] Booting worker with pid: 15740
[2023-05-24 14:03:59 -0500] [15741] [INFO] Booting worker with pid: 15741
[2023-05-24 14:03:59 -0500] [15742] [INFO] Booting worker with pid: 15742
[2023-05-24 14:03:59 -0500] [15743] [INFO] Booting worker with pid: 15743
[2023-05-24 14:03:59 -0500] [15744] [INFO] Booting worker with pid: 15744
[2023-05-24 14:03:59 -0500] [15746] [INFO] Booting worker with pid: 15746
[2023-05-24 14:03:59 -0500] [15747] [INFO] Booting worker with pid: 15747
[2023-05-24 14:03:59 -0500] [15748] [INFO] Booting worker with pid: 15748
[2023-05-24 14:12:52 -0500] [15743] [INFO] Worker exiting (pid: 15743)
[2023-05-24 14:12:52 -0500] [15744] [INFO] Worker exiting (pid: 15744)
[2023-05-24 14:12:52 -0500] [15742] [INFO] Worker exiting (pid: 15742)
[2023-05-24 14:12:52 -0500] [15746] [INFO] Worker exiting (pid: 15746)
[2023-05-24 14:12:52 -0500] [15740] [INFO] Worker exiting (pid: 15740)
[2023-05-24 14:12:52 -0500] [15741] [INFO] Worker exiting (pid: 15741)
[2023-05-24 14:12:52 -0500] [15736] [INFO] Worker exiting (pid: 15736)
[2023-05-24 14:12:52 -0500] [15747] [INFO] Worker exiting (pid: 15747)
[2023-05-24 14:12:52 -0500] [15748] [INFO] Worker exiting (pid: 15748)
[2023-05-24 14:12:55 -0500] [15716] [INFO] Handling signal: term
[2023-05-24 14:13:09 -0500] [15716] [WARNING] Worker with pid 15736 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15743 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15744 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15746 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15747 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15748 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15740 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15742 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [WARNING] Worker with pid 15741 was terminated due to signal 15
[2023-05-24 14:13:11 -0500] [15716] [INFO] Shutting down: Master
[2023-05-24 14:13:17 -0500] [16393] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:13:17 -0500] [16393] [INFO] Listening at: http://127.0.0.1:5000 (16393)
[2023-05-24 14:13:17 -0500] [16393] [INFO] Using worker: sync
[2023-05-24 14:13:17 -0500] [16408] [INFO] Booting worker with pid: 16408
[2023-05-24 14:13:17 -0500] [16409] [INFO] Booting worker with pid: 16409
[2023-05-24 14:13:17 -0500] [16410] [INFO] Booting worker with pid: 16410
[2023-05-24 14:13:17 -0500] [16411] [INFO] Booting worker with pid: 16411
[2023-05-24 14:13:17 -0500] [16412] [INFO] Booting worker with pid: 16412
[2023-05-24 14:13:17 -0500] [16413] [INFO] Booting worker with pid: 16413
[2023-05-24 14:13:18 -0500] [16414] [INFO] Booting worker with pid: 16414
[2023-05-24 14:13:18 -0500] [16415] [INFO] Booting worker with pid: 16415
[2023-05-24 14:13:18 -0500] [16416] [INFO] Booting worker with pid: 16416
[2023-05-24 14:30:35 -0500] [16412] [INFO] Worker exiting (pid: 16412)
[2023-05-24 14:30:35 -0500] [16411] [INFO] Worker exiting (pid: 16411)
[2023-05-24 14:30:35 -0500] [16416] [INFO] Worker exiting (pid: 16416)
[2023-05-24 14:30:35 -0500] [16393] [INFO] Handling signal: term
[2023-05-24 14:30:35 -0500] [16408] [INFO] Worker exiting (pid: 16408)
[2023-05-24 14:30:35 -0500] [16410] [INFO] Worker exiting (pid: 16410)
[2023-05-24 14:30:35 -0500] [16415] [INFO] Worker exiting (pid: 16415)
[2023-05-24 14:30:35 -0500] [16414] [INFO] Worker exiting (pid: 16414)
[2023-05-24 14:30:35 -0500] [16393] [WARNING] Worker with pid 16411 was terminated due to signal 15
[2023-05-24 14:30:35 -0500] [16413] [INFO] Worker exiting (pid: 16413)
[2023-05-24 14:30:35 -0500] [16409] [INFO] Worker exiting (pid: 16409)
[2023-05-24 14:30:35 -0500] [16393] [WARNING] Worker with pid 16415 was terminated due to signal 15
[2023-05-24 14:30:35 -0500] [16393] [WARNING] Worker with pid 16412 was terminated due to signal 15
[2023-05-24 14:30:35 -0500] [16393] [WARNING] Worker with pid 16416 was terminated due to signal 15
[2023-05-24 14:30:35 -0500] [16393] [WARNING] Worker with pid 16414 was terminated due to signal 15
[2023-05-24 14:30:35 -0500] [16393] [INFO] Shutting down: Master
[2023-05-24 14:30:35 -0500] [17814] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:30:35 -0500] [17814] [INFO] Listening at: http://127.0.0.1:5000 (17814)
[2023-05-24 14:30:35 -0500] [17814] [INFO] Using worker: sync
[2023-05-24 14:30:35 -0500] [17817] [INFO] Booting worker with pid: 17817
[2023-05-24 14:30:36 -0500] [17818] [INFO] Booting worker with pid: 17818
[2023-05-24 14:30:36 -0500] [17828] [INFO] Booting worker with pid: 17828
[2023-05-24 14:30:36 -0500] [17829] [INFO] Booting worker with pid: 17829
[2023-05-24 14:30:36 -0500] [17830] [INFO] Booting worker with pid: 17830
[2023-05-24 14:30:36 -0500] [17831] [INFO] Booting worker with pid: 17831
[2023-05-24 14:30:36 -0500] [17832] [INFO] Booting worker with pid: 17832
[2023-05-24 14:30:36 -0500] [17833] [INFO] Booting worker with pid: 17833
[2023-05-24 14:30:36 -0500] [17834] [INFO] Booting worker with pid: 17834
[2023-05-24 14:31:08 -0500] [17817] [INFO] Worker exiting (pid: 17817)
[2023-05-24 14:31:08 -0500] [17814] [INFO] Handling signal: term
[2023-05-24 14:31:08 -0500] [17818] [INFO] Worker exiting (pid: 17818)
[2023-05-24 14:31:08 -0500] [17829] [INFO] Worker exiting (pid: 17829)
[2023-05-24 14:31:08 -0500] [17833] [INFO] Worker exiting (pid: 17833)
[2023-05-24 14:31:08 -0500] [17828] [INFO] Worker exiting (pid: 17828)
[2023-05-24 14:31:08 -0500] [17834] [INFO] Worker exiting (pid: 17834)
[2023-05-24 14:31:08 -0500] [17830] [INFO] Worker exiting (pid: 17830)
[2023-05-24 14:31:08 -0500] [17831] [INFO] Worker exiting (pid: 17831)
[2023-05-24 14:31:08 -0500] [17832] [INFO] Worker exiting (pid: 17832)
[2023-05-24 14:31:09 -0500] [17814] [INFO] Shutting down: Master
[2023-05-24 14:31:09 -0500] [17947] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:31:09 -0500] [17947] [INFO] Listening at: http://192.168.1.203:5000 (17947)
[2023-05-24 14:31:09 -0500] [17947] [INFO] Using worker: sync
[2023-05-24 14:31:09 -0500] [17949] [INFO] Booting worker with pid: 17949
[2023-05-24 14:31:09 -0500] [17950] [INFO] Booting worker with pid: 17950
[2023-05-24 14:31:09 -0500] [17951] [INFO] Booting worker with pid: 17951
[2023-05-24 14:31:09 -0500] [17952] [INFO] Booting worker with pid: 17952
[2023-05-24 14:31:09 -0500] [17953] [INFO] Booting worker with pid: 17953
[2023-05-24 14:31:09 -0500] [17954] [INFO] Booting worker with pid: 17954
[2023-05-24 14:31:09 -0500] [17955] [INFO] Booting worker with pid: 17955
[2023-05-24 14:31:09 -0500] [17956] [INFO] Booting worker with pid: 17956
[2023-05-24 14:31:10 -0500] [17957] [INFO] Booting worker with pid: 17957
[2023-05-24 14:34:25 -0500] [17947] [INFO] Handling signal: term
[2023-05-24 14:34:25 -0500] [17949] [INFO] Worker exiting (pid: 17949)
[2023-05-24 14:34:25 -0500] [17954] [INFO] Worker exiting (pid: 17954)
[2023-05-24 14:34:25 -0500] [17953] [INFO] Worker exiting (pid: 17953)
[2023-05-24 14:34:25 -0500] [17956] [INFO] Worker exiting (pid: 17956)
[2023-05-24 14:34:25 -0500] [17955] [INFO] Worker exiting (pid: 17955)
[2023-05-24 14:34:25 -0500] [17952] [INFO] Worker exiting (pid: 17952)
[2023-05-24 14:34:25 -0500] [17951] [INFO] Worker exiting (pid: 17951)
[2023-05-24 14:34:25 -0500] [17950] [INFO] Worker exiting (pid: 17950)
[2023-05-24 14:34:25 -0500] [17957] [INFO] Worker exiting (pid: 17957)
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17950 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17949 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17951 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17952 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17953 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17954 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17955 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17956 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [WARNING] Worker with pid 17957 was terminated due to signal 15
[2023-05-24 14:34:25 -0500] [17947] [INFO] Shutting down: Master
[2023-05-24 14:34:28 -0500] [18404] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:34:28 -0500] [18404] [INFO] Listening at: http://192.168.1.203:5000 (18404)
[2023-05-24 14:34:28 -0500] [18404] [INFO] Using worker: sync
[2023-05-24 14:34:28 -0500] [18418] [INFO] Booting worker with pid: 18418
[2023-05-24 14:34:28 -0500] [18419] [INFO] Booting worker with pid: 18419
[2023-05-24 14:34:28 -0500] [18423] [INFO] Booting worker with pid: 18423
[2023-05-24 14:34:29 -0500] [18424] [INFO] Booting worker with pid: 18424
[2023-05-24 14:34:29 -0500] [18425] [INFO] Booting worker with pid: 18425
[2023-05-24 14:34:29 -0500] [18426] [INFO] Booting worker with pid: 18426
[2023-05-24 14:34:29 -0500] [18427] [INFO] Booting worker with pid: 18427
[2023-05-24 14:34:29 -0500] [18428] [INFO] Booting worker with pid: 18428
[2023-05-24 14:34:29 -0500] [18429] [INFO] Booting worker with pid: 18429
[2023-05-24 14:35:30 -0500] [18428] [ERROR] Error handling request /api/auth/login
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'user.secondary_email' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/views/auth.py", line 42, in post
    user = User.query.filter_by(email=body.get('email')).first()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2762, in first
    return self.limit(1)._iter().first()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'user.secondary_email' in 'field list'")
[SQL: SELECT user.id AS user_id, user.first_name AS user_first_name, user.middle_name AS user_middle_name, user.last_name AS user_last_name, user.access_id AS user_access_id, user.email AS user_email, user.secondary_email AS user_secondary_email, user.linkedin AS user_linkedin, user.password AS user_password, user.address AS user_address, user.address2 AS user_address2, user.city AS user_city, user.state AS user_state, user.zip_code AS user_zip_code, user.country AS user_country, user.telephone AS user_telephone, user.active AS user_active 
FROM user 
WHERE user.email = lower(%(lower_1)s) 
 LIMIT %(param_1)s]
[parameters: {'lower_1': 'admin@mail.com', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/website-stuff/backend/views/auth.py", line 52, in post
    raise InternalServerError
helpers.Error.InternalServerError
[2023-05-24 14:48:18 -0500] [18427] [INFO] Worker exiting (pid: 18427)
[2023-05-24 14:48:18 -0500] [18423] [INFO] Worker exiting (pid: 18423)
[2023-05-24 14:48:18 -0500] [18426] [INFO] Worker exiting (pid: 18426)
[2023-05-24 14:48:18 -0500] [18418] [INFO] Worker exiting (pid: 18418)
[2023-05-24 14:48:18 -0500] [18428] [INFO] Worker exiting (pid: 18428)
[2023-05-24 14:48:18 -0500] [18429] [INFO] Worker exiting (pid: 18429)
[2023-05-24 14:48:18 -0500] [18425] [INFO] Worker exiting (pid: 18425)
[2023-05-24 14:48:18 -0500] [18419] [INFO] Worker exiting (pid: 18419)
[2023-05-24 14:48:18 -0500] [18424] [INFO] Worker exiting (pid: 18424)
[2023-05-24 14:48:18 -0500] [18404] [INFO] Handling signal: term
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18419 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18429 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18427 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18418 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18424 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18426 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18423 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18428 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [WARNING] Worker with pid 18425 was terminated due to signal 15
[2023-05-24 14:48:19 -0500] [18404] [INFO] Shutting down: Master
[2023-05-24 14:49:16 -0500] [19492] [INFO] Starting gunicorn 20.1.0
[2023-05-24 14:49:16 -0500] [19492] [INFO] Listening at: http://192.168.1.203:5000 (19492)
[2023-05-24 14:49:16 -0500] [19492] [INFO] Using worker: sync
[2023-05-24 14:49:16 -0500] [19494] [INFO] Booting worker with pid: 19494
[2023-05-24 14:49:16 -0500] [19495] [INFO] Booting worker with pid: 19495
[2023-05-24 14:49:17 -0500] [19496] [INFO] Booting worker with pid: 19496
[2023-05-24 14:49:17 -0500] [19497] [INFO] Booting worker with pid: 19497
[2023-05-24 14:49:17 -0500] [19498] [INFO] Booting worker with pid: 19498
[2023-05-24 14:49:17 -0500] [19499] [INFO] Booting worker with pid: 19499
[2023-05-24 14:49:17 -0500] [19500] [INFO] Booting worker with pid: 19500
[2023-05-24 14:49:17 -0500] [19501] [INFO] Booting worker with pid: 19501
[2023-05-24 14:49:17 -0500] [19502] [INFO] Booting worker with pid: 19502
[2023-05-24 14:52:50 -0500] [19498] [ERROR] Error handling request /api/pows?filter={%22status%22:[%22eq%22,%22Pending%20Graduation%22]}&order=%22%22&page=1&per_page=10
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'sis_portal.pow' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/var/www/website-stuff/backend/views/POW.py", line 31, in get
    raise e
  File "/var/www/website-stuff/backend/views/POW.py", line 29, in get
    return pows_schema.dump(results.all()), 200
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2711, in all
    return self._iter().all()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1611, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1478, in _execute_clauseelement
    ret = self._execute_context(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    self._handle_dbapi_exception(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2023, in _handle_dbapi_exception
    util.raise_(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1799, in _execute_context
    self.dialect.do_execute(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'sis_portal.pow' doesn't exist")
[SQL: SELECT pow.id AS pow_id, pow.student_id AS pow_student_id, pow.creation_date AS pow_creation_date, pow.petition_date AS pow_petition_date, pow.candidacy_approved_by_id AS pow_candidacy_approved_by_id, pow.candidacy_approval_date AS pow_candidacy_approval_date, pow.graduation_approved_by_id AS pow_graduation_approved_by_id, pow.graduation_approval_date AS pow_graduation_approval_date, pow.specialization_id AS pow_specialization_id, pow.orientation_term_id AS pow_orientation_term_id, pow.first_class_term_id AS pow_first_class_term_id, pow.`status` AS pow_status, pow.completion_date AS pow_completion_date 
FROM pow 
WHERE pow.`status` = %(status_1)s]
[parameters: {'status_1': 'Pending Graduation'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2023-05-24 14:53:21 -0500] [19492] [CRITICAL] WORKER TIMEOUT (pid:19500)
[2023-05-24 14:53:22 -0500] [19500] [INFO] Worker exiting (pid: 19500)
[2023-05-24 14:53:22 -0500] [19937] [INFO] Booting worker with pid: 19937
[2023-05-24 14:54:26 -0500] [19494] [INFO] Worker exiting (pid: 19494)
[2023-05-24 14:54:26 -0500] [19495] [INFO] Worker exiting (pid: 19495)
[2023-05-24 14:54:26 -0500] [19492] [INFO] Handling signal: term
[2023-05-24 14:54:26 -0500] [19937] [INFO] Worker exiting (pid: 19937)
[2023-05-24 14:54:26 -0500] [19499] [INFO] Worker exiting (pid: 19499)
[2023-05-24 14:54:26 -0500] [19496] [INFO] Worker exiting (pid: 19496)
[2023-05-24 14:54:26 -0500] [19497] [INFO] Worker exiting (pid: 19497)
[2023-05-24 14:54:26 -0500] [19498] [INFO] Worker exiting (pid: 19498)
[2023-05-24 14:54:26 -0500] [19502] [INFO] Worker exiting (pid: 19502)
[2023-05-24 14:54:26 -0500] [19501] [INFO] Worker exiting (pid: 19501)
[2023-05-24 14:54:26 -0500] [19492] [WARNING] Worker with pid 19495 was terminated due to signal 15
[2023-05-24 14:54:26 -0500] [19492] [WARNING] Worker with pid 19494 was terminated due to signal 15
[2023-05-24 14:54:26 -0500] [19492] [INFO] Shutting down: Master
[2023-05-24 16:22:51 -0500] [23867] [INFO] Starting gunicorn 20.1.0
[2023-05-24 16:22:51 -0500] [23867] [INFO] Listening at: http://192.168.1.203:5000 (23867)
[2023-05-24 16:22:51 -0500] [23867] [INFO] Using worker: sync
[2023-05-24 16:22:51 -0500] [23869] [INFO] Booting worker with pid: 23869
[2023-05-24 16:22:51 -0500] [23870] [INFO] Booting worker with pid: 23870
[2023-05-24 16:22:51 -0500] [23871] [INFO] Booting worker with pid: 23871
[2023-05-24 16:22:51 -0500] [23872] [INFO] Booting worker with pid: 23872
[2023-05-24 16:22:52 -0500] [23873] [INFO] Booting worker with pid: 23873
[2023-05-24 16:22:52 -0500] [23874] [INFO] Booting worker with pid: 23874
[2023-05-24 16:22:52 -0500] [23875] [INFO] Booting worker with pid: 23875
[2023-05-24 16:22:52 -0500] [23876] [INFO] Booting worker with pid: 23876
[2023-05-24 16:22:52 -0500] [23877] [INFO] Booting worker with pid: 23877
[2023-05-24 16:30:19 -0500] [23867] [INFO] Handling signal: term
[2023-05-24 16:30:20 -0500] [23870] [INFO] Worker exiting (pid: 23870)
[2023-05-24 16:30:20 -0500] [23872] [INFO] Worker exiting (pid: 23872)
[2023-05-24 16:30:20 -0500] [23871] [INFO] Worker exiting (pid: 23871)
[2023-05-24 16:30:20 -0500] [23869] [INFO] Worker exiting (pid: 23869)
[2023-05-24 16:30:20 -0500] [23875] [INFO] Worker exiting (pid: 23875)
[2023-05-24 16:30:20 -0500] [23874] [INFO] Worker exiting (pid: 23874)
[2023-05-24 16:30:20 -0500] [23873] [INFO] Worker exiting (pid: 23873)
[2023-05-24 16:30:20 -0500] [23876] [INFO] Worker exiting (pid: 23876)
[2023-05-24 16:30:20 -0500] [23877] [INFO] Worker exiting (pid: 23877)
[2023-05-24 16:30:23 -0500] [23867] [WARNING] Worker with pid 23869 was terminated due to signal 15
[2023-05-24 16:30:23 -0500] [23867] [WARNING] Worker with pid 23871 was terminated due to signal 15
[2023-05-24 16:30:23 -0500] [23867] [WARNING] Worker with pid 23874 was terminated due to signal 15
[2023-05-24 16:30:23 -0500] [23867] [WARNING] Worker with pid 23872 was terminated due to signal 15
[2023-05-24 16:30:29 -0500] [23867] [INFO] Shutting down: Master
[2023-05-26 09:44:02 -0500] [1050] [INFO] Starting gunicorn 20.1.0
[2023-05-26 09:44:02 -0500] [1050] [ERROR] Invalid address: ('192.168.1.203', 5000)
[2023-05-26 09:44:02 -0500] [1050] [ERROR] Retrying in 1 second.
[2023-05-26 09:44:03 -0500] [1050] [ERROR] Connection in use: ('192.168.1.203', 5000)
[2023-05-26 09:44:03 -0500] [1050] [ERROR] Retrying in 1 second.
[2023-05-26 09:44:04 -0500] [1050] [ERROR] Connection in use: ('192.168.1.203', 5000)
[2023-05-26 09:44:04 -0500] [1050] [ERROR] Retrying in 1 second.
[2023-05-26 09:44:05 -0500] [1050] [ERROR] Connection in use: ('192.168.1.203', 5000)
[2023-05-26 09:44:05 -0500] [1050] [ERROR] Retrying in 1 second.
[2023-05-26 09:44:06 -0500] [1050] [ERROR] Connection in use: ('192.168.1.203', 5000)
[2023-05-26 09:44:06 -0500] [1050] [ERROR] Retrying in 1 second.
[2023-05-26 09:44:07 -0500] [1050] [ERROR] Can't connect to ('192.168.1.203', 5000)
[2023-05-26 09:55:06 -0500] [6611] [INFO] Starting gunicorn 20.1.0
[2023-05-26 09:55:06 -0500] [6611] [INFO] Listening at: http://192.168.1.203:5000 (6611)
[2023-05-26 09:55:06 -0500] [6611] [INFO] Using worker: sync
[2023-05-26 09:55:06 -0500] [6628] [INFO] Booting worker with pid: 6628
[2023-05-26 09:55:06 -0500] [6629] [INFO] Booting worker with pid: 6629
[2023-05-26 09:55:06 -0500] [6630] [INFO] Booting worker with pid: 6630
[2023-05-26 09:55:06 -0500] [6631] [INFO] Booting worker with pid: 6631
[2023-05-26 09:55:06 -0500] [6632] [INFO] Booting worker with pid: 6632
[2023-05-26 09:55:06 -0500] [6633] [INFO] Booting worker with pid: 6633
[2023-05-26 09:55:06 -0500] [6634] [INFO] Booting worker with pid: 6634
[2023-05-26 09:55:06 -0500] [6635] [INFO] Booting worker with pid: 6635
[2023-05-26 09:55:06 -0500] [6636] [INFO] Booting worker with pid: 6636
[2023-05-26 10:06:08 -0500] [6630] [INFO] Worker exiting (pid: 6630)
[2023-05-26 10:06:08 -0500] [6633] [INFO] Worker exiting (pid: 6633)
[2023-05-26 10:06:08 -0500] [6628] [INFO] Worker exiting (pid: 6628)
[2023-05-26 10:06:08 -0500] [6631] [INFO] Worker exiting (pid: 6631)
[2023-05-26 10:06:08 -0500] [6636] [INFO] Worker exiting (pid: 6636)
[2023-05-26 10:06:08 -0500] [6635] [INFO] Worker exiting (pid: 6635)
[2023-05-26 10:06:08 -0500] [6632] [INFO] Worker exiting (pid: 6632)
[2023-05-26 10:06:08 -0500] [6634] [INFO] Worker exiting (pid: 6634)
[2023-05-26 10:06:09 -0500] [6629] [INFO] Worker exiting (pid: 6629)
[2023-05-26 10:06:15 -0500] [6611] [INFO] Handling signal: term
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6629 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6630 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6631 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6632 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6633 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6634 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6635 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6636 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [WARNING] Worker with pid 6628 was terminated due to signal 15
[2023-05-26 10:06:33 -0500] [6611] [INFO] Shutting down: Master
[2023-05-26 10:06:45 -0500] [7348] [INFO] Starting gunicorn 20.1.0
[2023-05-26 10:06:45 -0500] [7348] [INFO] Listening at: http://192.168.1.203:5000 (7348)
[2023-05-26 10:06:45 -0500] [7348] [INFO] Using worker: sync
[2023-05-26 10:06:45 -0500] [7384] [INFO] Booting worker with pid: 7384
[2023-05-26 10:06:45 -0500] [7385] [INFO] Booting worker with pid: 7385
[2023-05-26 10:06:45 -0500] [7386] [INFO] Booting worker with pid: 7386
[2023-05-26 10:06:45 -0500] [7387] [INFO] Booting worker with pid: 7387
[2023-05-26 10:06:45 -0500] [7388] [INFO] Booting worker with pid: 7388
[2023-05-26 10:06:45 -0500] [7389] [INFO] Booting worker with pid: 7389
[2023-05-26 10:06:45 -0500] [7390] [INFO] Booting worker with pid: 7390
[2023-05-26 10:06:45 -0500] [7391] [INFO] Booting worker with pid: 7391
[2023-05-26 10:06:45 -0500] [7392] [INFO] Booting worker with pid: 7392
[2023-05-26 12:03:46 -0500] [7387] [ERROR] Error handling request /api/users
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/var/www/website-stuff/backend/views/user.py", line 82, in post
    raise e
  File "/var/www/website-stuff/backend/views/user.py", line 60, in post
    user = new_user_schema.load(body, session=db.session)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 96, in load
    return super().load(data, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 719, in load
    return self._do_load(
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/marshmallow/schema.py", line 901, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'secondaryEmail': ['Unknown field.']}
[2023-05-26 12:05:28 -0500] [7348] [INFO] Handling signal: term
[2023-05-26 12:05:28 -0500] [7384] [INFO] Worker exiting (pid: 7384)
[2023-05-26 12:05:28 -0500] [7386] [INFO] Worker exiting (pid: 7386)
[2023-05-26 12:05:28 -0500] [7385] [INFO] Worker exiting (pid: 7385)
[2023-05-26 12:05:28 -0500] [7387] [INFO] Worker exiting (pid: 7387)
[2023-05-26 12:05:28 -0500] [7388] [INFO] Worker exiting (pid: 7388)
[2023-05-26 12:05:28 -0500] [7391] [INFO] Worker exiting (pid: 7391)
[2023-05-26 12:05:28 -0500] [7390] [INFO] Worker exiting (pid: 7390)
[2023-05-26 12:05:28 -0500] [7389] [INFO] Worker exiting (pid: 7389)
[2023-05-26 12:05:28 -0500] [7392] [INFO] Worker exiting (pid: 7392)
[2023-05-26 12:05:29 -0500] [7348] [INFO] Shutting down: Master
[2023-05-26 12:05:29 -0500] [9759] [INFO] Starting gunicorn 20.1.0
[2023-05-26 12:05:29 -0500] [9759] [INFO] Listening at: http://192.168.1.203:5000 (9759)
[2023-05-26 12:05:29 -0500] [9759] [INFO] Using worker: sync
[2023-05-26 12:05:29 -0500] [9762] [INFO] Booting worker with pid: 9762
[2023-05-26 12:05:29 -0500] [9763] [INFO] Booting worker with pid: 9763
[2023-05-26 12:05:29 -0500] [9764] [INFO] Booting worker with pid: 9764
[2023-05-26 12:05:29 -0500] [9765] [INFO] Booting worker with pid: 9765
[2023-05-26 12:05:29 -0500] [9766] [INFO] Booting worker with pid: 9766
[2023-05-26 12:05:29 -0500] [9767] [INFO] Booting worker with pid: 9767
[2023-05-26 12:05:29 -0500] [9768] [INFO] Booting worker with pid: 9768
[2023-05-26 12:05:29 -0500] [9769] [INFO] Booting worker with pid: 9769
[2023-05-26 12:05:29 -0500] [9770] [INFO] Booting worker with pid: 9770
[2023-05-26 12:27:01 -0500] [9762] [INFO] Worker exiting (pid: 9762)
[2023-05-26 12:27:01 -0500] [9767] [INFO] Worker exiting (pid: 9767)
[2023-05-26 12:27:01 -0500] [9766] [INFO] Worker exiting (pid: 9766)
[2023-05-26 12:27:01 -0500] [9768] [INFO] Worker exiting (pid: 9768)
[2023-05-26 12:27:01 -0500] [9769] [INFO] Worker exiting (pid: 9769)
[2023-05-26 12:27:01 -0500] [9759] [INFO] Handling signal: term
[2023-05-26 12:27:01 -0500] [9763] [INFO] Worker exiting (pid: 9763)
[2023-05-26 12:27:01 -0500] [9770] [INFO] Worker exiting (pid: 9770)
[2023-05-26 12:27:01 -0500] [9764] [INFO] Worker exiting (pid: 9764)
[2023-05-26 12:27:01 -0500] [9765] [INFO] Worker exiting (pid: 9765)
[2023-05-26 12:27:01 -0500] [9759] [WARNING] Worker with pid 9769 was terminated due to signal 15
[2023-05-26 12:27:01 -0500] [9759] [WARNING] Worker with pid 9767 was terminated due to signal 15
[2023-05-26 12:27:01 -0500] [9759] [WARNING] Worker with pid 9768 was terminated due to signal 15
[2023-05-26 12:27:02 -0500] [9759] [INFO] Shutting down: Master
[2023-05-26 12:27:02 -0500] [10328] [INFO] Starting gunicorn 20.1.0
[2023-05-26 12:27:02 -0500] [10328] [INFO] Listening at: http://192.168.1.203:5000 (10328)
[2023-05-26 12:27:02 -0500] [10328] [INFO] Using worker: sync
[2023-05-26 12:27:02 -0500] [10340] [INFO] Booting worker with pid: 10340
[2023-05-26 12:27:02 -0500] [10341] [INFO] Booting worker with pid: 10341
[2023-05-26 12:27:02 -0500] [10342] [INFO] Booting worker with pid: 10342
[2023-05-26 12:27:02 -0500] [10343] [INFO] Booting worker with pid: 10343
[2023-05-26 12:27:02 -0500] [10344] [INFO] Booting worker with pid: 10344
[2023-05-26 12:27:02 -0500] [10345] [INFO] Booting worker with pid: 10345
[2023-05-26 12:27:03 -0500] [10346] [INFO] Booting worker with pid: 10346
[2023-05-26 12:27:03 -0500] [10347] [INFO] Booting worker with pid: 10347
[2023-05-26 12:27:03 -0500] [10348] [INFO] Booting worker with pid: 10348
[2023-05-26 13:00:58 -0500] [10342] [ERROR] Error handling request /api/auth/login
Traceback (most recent call last):
  File "/var/www/website-stuff/backend/views/auth.py", line 45, in post
    raise UnauthorizedError
helpers.Error.UnauthorizedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/website-stuff/backend/venv/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/website-stuff/backend/views/auth.py", line 50, in post
    raise UnauthorizedError
helpers.Error.UnauthorizedError
